Create 2 pages home and about
ice949/First-Capstone pull request #1
Opened 2022-05-20 09:31 UTC by ice949

## HTML/CSS & JavaScript capstone project - Conference page

In this project I did the following
- Used semantic HTML tags.
- Applied best practices in HTML code.
- Used CSS selectors correctly.
- Used CSS box model.
- Used Flexbox to place elements in the page.
- Used media queries to make site responsive to screen sizes
- Used GitHub Pages to deploy web pages.
- Applied JavaScript best practices and language style guides in code.
- Used JavaScript to manipulate DOM elements.
- Used JavaScript events.
- Used objects to store and access data.
- Recorded a video describeing the site https://www.loom.com/share/27dbbce8ebe44d9ba40bae6fa464b5f4

2022-05-20 10:17 UTC, sja-thedude requested changes
Hi @ice949, This is @sja-thedude your code reviewer.

Good job so far!
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!

![first review](https://user-images.githubusercontent.com/70269507/163608525-162336d7-2c8d-4cfd-a86e-ed9edb0852f9.gif)

## Suggested changes
- [ ] _Check the comments under the review._
##  Make sure to watch the loom video attached to have a better understanding.

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you consider them as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-05-20 10:17 UTC, sja-thedude commented on index.html
> +        <div class="toggleMenu">
- [ ] Kindly make sure to view this loom [VIDEO](https://www.loom.com/share/d245a79c7c434208b7b59a199d3e9a21), in order to understand what all changes are to be made.
- [ ] Kindly make sure to align all the elements shown in the video properly.
- [ ] kindly make sure to add the hover effect to articles as suggested in the video.
- [ ] Kindly make sure to follow the same font size as per the design.
- [ ] Kindly follow the same mobile menu colour for about mobile menu a home mobile menu suggested in the video.
- [ ] Kindly add the checks background image to all the images and align them properly.
- [ ] Kindly make sure the images in the speaker's section are in 2 columns instead of 3.
- [ ] Kindly follow the same background colour for the sections I suggested in the video.

2022-05-20 10:17 UTC, sja-thedude commented on index.html
> +        <h1 class="title">NATIONAL INNOVATION INITIATIVE 2022</h1>
- [ ] Kindly change the colour of this h1 as shown in the [video](https://www.loom.com/share/23198e96919f4dc59eef67382c0cc6c4).

2022-05-20 11:04 UTC, ice949 commented on index.html
> +        <h1 class="title">NATIONAL INNOVATION INITIATIVE 2022</h1>
@sja-thedude All this changes haaa, you want me to repeat

2022-05-21 12:51 UTC, m05e5 requested changes
Hi @ice949 , 

Good job so far. I really like what you did!
There are some issues that you still need to work on to go to the next project but you are almost there!
![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Highlights


## Required Changes ♻️
* You really did a great job but there are some features you need to improve

- [ ] **_Please check the comments below_**

_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-21 12:51 UTC, m05e5 commented on main.js
> +});
- Hi Great job on implementing most of the previous reviewer suggestions. As mentioned by the previous reviewer, you're supposed to stick to the design as much as possible. So kindly make the text and images be aside 
- **imp**
![image](https://user-images.githubusercontent.com/37901469/169652091-0a63faf8-7438-4ea5-87b3-c802fcdebb5a.png)
**design**
![image](https://user-images.githubusercontent.com/37901469/169652181-04ca23c5-cc9e-43a9-87f2-c7bc7722e29b.png)

2022-05-21 13:12 UTC, uche-inyama approved these changes
## Hi @ice949 :slightly_smiling_face:  

Your project is complete!  Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-21 13:33 UTC, merged